### ISSUE TITLE
Crash with VLC and cover options v1.5.0

### ISSUE THREAD

**Issue by COOLIGUAY** [univrsal/tuna#53]
With "Try downloading cover" enabled and VLC as song source, OBS slows down and lags.
Finally it crashes.

https://obsproject.com/logs/vxoD6AsSRRj8RdDW

Also with VLC don't show the song info in the .txt, only the letters of the song format ("%m - %t" shows "m - t" in the file).

**Comment by GavAttack** [comment]
I am having this same issue after updating Tuna

**Comment by univrsal** [comment]
Seems to be a general problem, I tested it on windows and it crashes as soon as I start the plugin.

**Comment by geslotencirkel** [comment]
same issue with the song info text not getting pulled into txt file correctly.
Length and Time remaining works though

**Comment by univrsal** [comment]
Something is really broken with the music control dock. I'm considering to remove it, because it's caused mostly issues with little gain. It works fine for me on linux, but on Windows it just crashes. I think it has to do something with different Qt versions, but I don't know if I want to spend time looking into it.

**Comment by COOLIGUAY** [comment]
I don't remember exactly, but i think i tried a nightly on the 14th and it worked fine.

It's an incredible plugin with and without the dock, the main function is more than fulfilled.
Whatever you choose will be the right thing.

Thank you very much for your effort!

**Comment by univrsal** [comment]
I'll try the nightlies and see if I can find which one it was. The problem is that a part of the dock didn't really work and I think when I tried to make it work things started to break.

**Comment by COOLIGUAY** [comment]
If it helps, I have tried the latest nightly (Changed up some stuff in music dock state syncing) and both text and covers work on windows and vlc again.

Sometimes obs it's lagged. It feels like it works fine when it finds a cover, but lags when the file doesn't have one.
[tuna] Couldn't fetch file from n/a to C:/Stream/Tuna/cover.png.tmp

**Comment by univrsal** [comment]
After some testing it seems like MPD on windows blocks the refresh thread, which in turn blocks the UI thread because it's waiting for the refresh thread. I'm not sure how it's connected to the VLC issue, but I have a feeling it might be that the UI isn't showing the correct source. (So it might show VLC but it's actually trying to pull information from MPD, which fails because you don't have MPD running).

**Comment by univrsal** [comment]
Please try the latest nightly and test if the issue still persists

**Comment by COOLIGUAY** [comment]
Nice! The issue seems to have disappeared.

I have tried next/previous song from the dock (VLC) and songs without cover causes lag.
But that is a different issue.

A less annoying problem, OBS crash on exit:
https://obsproject.com/logs/nZiibLTN8-WQkI7x

**Comment by geslotencirkel** [comment]
are the nightlies pre-built?

**Comment by univrsal** [comment]
There's a new nightly, which fixes the gui issues, try and see if it still crashes on exit. I'll rewrite the VLC source once obs 26.0.0 comes out which will make it more stable.

**Comment by COOLIGUAY** [comment]
Thank you very much for all your effort!

Still crashing on exit with VLC, everything else works fine.

https://obsproject.com/logs/GeSoBZj-Iyo7lNDU

**Comment by univrsal** [comment]
I think I know what the issue is, the VLC library gets unloaded before tuna stops looking for song information, which crashes because it expects it to be there. Should be an easy fix if that's the cause
