### ISSUE TITLE
macOS version no longer shows up at all - please remove

### ISSUE THREAD

**Issue by crystalllized** [univrsal/tuna#72]
Hi! I saw that you were planning to stop offering Mac support now (though, only after I downloaded and installed the package since it isn't mentioned on the latest release) and I just want to let you know that even after bypassing Gatekeeper to run the package and rebooting several times, nothing ever shows up in OBS for Tuna. If you aren't planning to offer support anymore, could you remove the package from the offering entirely so people like me don't get excited to have actually found a Now Playing plugin that works on the Mac with VLC, download it, and then find that it doesn't do anything at all?

**Comment by univrsal** [comment]
I made it fairly obvious that I don't offer support for macOS, both on the obs forums and in the macOS installer. Out of the three platforms, developing for it is the worst by a landslide.
That said the issue was nothing major so I went ahead and fixed it, just redownload the installer. Also for future bug reports to the obs developers or for obs plugins I'd highly recommend you include the log file, because it would've saved me from digging up my macOS installation to find out what the issue was.
