### ISSUE TITLE
Soundcloud support with cover?

### ISSUE THREAD

**Issue by reaaLx** [univrsal/tuna#79]
Hello i believe [NowSniper](https://github.com/TheArmagan/NowSniper) has a unique way of getting Soundcloud information and was wondering, maybe you can pull request it to perhaps merge the ideas together?

**Comment by univrsal** [comment]
I might be able to add this, but I might tweak the script.

**Comment by univrsal** [comment]
![image](https://user-images.githubusercontent.com/8353672/96321240-2d3fc680-1004-11eb-9557-3fb12eb8be61.png)
Turned out to be a fairly easy task, I added it in 4d4aed02e9edb9d6355fb604495824a539ebabe8. As I said I have modified the script from NowSniper to use POST instead of a websocket, because I already have a HTTP server running and didn't want to start a separate websocket server.
The script can be found [here](https://greasyfork.org/en/scripts/413575-tuna-browser-script) although I'll put together more detailed information once I make a release with this.
Also thanks to @TheArmagan for the basis of the tampermonky script.
